# Activate with: --spring.profiles.active=postgres
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/legalcaseflow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
